server:
    port: 8081
spring:
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/cartinventory?useSSL=false
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true
      
# Test Details for Development Environment
test:
  details: CartInventory details for dev environment [From GitHub]
  engineer: Chandni
  department: Development Testing 
  engineerContact:
    email: chandni.dev@example.com
    phone: 222-343-7890       
