server:
    port: 8082
spring:
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/productservice?useSSL=false
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                
# Test Details for Development Environment
test:
  details: Product service details  [From GitHub]
  engineer: Chandni
  department: Development Testing
  engineerContact:
    email: chandni.dev@example.com
    phone: 123-456-7890                
